// GENERATED by scripts/i18n/build.mjs - do not edit; edit i18n/ko/plugins/<plugin>/*.json and run build again.
import { KO_01 } from './ko-dict-01'
export const KO: Record<string, string> = {}
Object.assign(KO, KO_01)
