// GENERATED by scripts/i18n/build.mjs - do not edit; edit i18n/ko/plugins/<plugin>/*.json and run build again.
import { KO_01 } from './ko-dict-01'
import { KO_02 } from './ko-dict-02'
import { KO_03 } from './ko-dict-03'
import { KO_04 } from './ko-dict-04'
import { KO_05 } from './ko-dict-05'
import { KO_06 } from './ko-dict-06'
import { KO_07 } from './ko-dict-07'
import { KO_08 } from './ko-dict-08'
import { KO_09 } from './ko-dict-09'
import { KO_10 } from './ko-dict-10'
import { KO_11 } from './ko-dict-11'
import { KO_12 } from './ko-dict-12'
import { KO_13 } from './ko-dict-13'
import { KO_14 } from './ko-dict-14'
export const KO: Record<string, string> = {}
Object.assign(KO, KO_01, KO_02, KO_03, KO_04, KO_05, KO_06, KO_07, KO_08, KO_09, KO_10, KO_11, KO_12, KO_13, KO_14)
