// GENERATED by scripts/i18n/templates/plugin-translate.ts - do not edit; edit the source and copy it again.
import { KO } from './ko-dict'

/** Plugin-side translator: one canonical copy, copied into every plugin as hooks/i18n/translate.ts. Pure, never throws, no I/O. */
export type Locale = 'ko' | 'en'
export const I18N_MARK: unique symbol = Symbol.for("ruflo.i18n.kit")

let locale: Locale = 'en'

/** /^en/i is English; anything else, unset included, is Korean. */
export function localeOf(value: unknown): Locale {
  return typeof value === 'string' && /^en/i.test(value) ? 'en' : 'ko'
}
export const setLocale = (next: Locale): void => void (locale = next === 'ko' ? 'ko' : 'en')
export const getLocale = (): Locale => locale

type Tpl = { st: string[]; kind: boolean[]; to: string; long: string; size: number; words: string[] }

const SYM = String.raw`(?:[✓✔✗✘✖•·⚠ℹ→▸►▶★☆*>?\-]|\p{Extended_Pictographic}️?)`
const LEAD = new RegExp(String.raw`^\s*(?:${SYM}+\s+)?`, 'u')
const HANGUL = /[가-힣]/
const GLUE = [': ', ' — ', ' - ', '= ']

let exact: Map<string, string> | null = null
let tpls: Tpl[] = []
let byWord = new Map<string, number[]>()
let always: number[] = []

function compile(): void {
  const map = new Map<string, string>()
  const list: Tpl[] = []
  for (const key of Object.keys(KO)) {
    const to = KO[key]
    if (typeof to !== 'string') continue
    if (!/\{\d+\}/.test(key)) { map.set(key, to); continue }
    const parts = key.split(/\{(\d+)\}/) // static, index, static, index, ..., static
    const n = (parts.length - 1) / 2
    const idx = parts.filter((_, i) => i % 2 === 1).map(Number)
    const statics = parts.filter((_, i) => i % 2 === 0)
    const sequential = idx.every((v, i) => v === i)
    const adjacent = statics.slice(1, -1).some(s => s === '')
    const letters = statics.join('').replace(/[^A-Za-z]/g, '').length
    const anchor = statics.some(s => /[A-Za-z]{4,}/.test(s))
    const need = [...to.matchAll(/\{(\d+)\}/g)].map(m => Number(m[1])).sort((a, b) => a - b)
    const same = need.length === n && need.every((v, i) => v === i)
    if (n === 0 || !sequential || adjacent || letters < 6 || !anchor || !same) continue

    // kind[k] true: the capture is one word (no whitespace); false: free text. Edge captures glued to a separator are free.
    const kind = idx.map((_, k) => {
      const first = k === 0 && statics[0] === ''
      const last = k === n - 1 && statics[n] === ''
      const glued = first ? GLUE.some(g => (statics[1] as string).startsWith(g)) : last ? GLUE.some(g => (statics[n - 1] as string).endsWith(g)) : false
      return (first || last) && !glued
    })
    const long = statics.reduce((a, s) => (s.length > a.length ? s : a), '')
    // Letter runs that no capture can lengthen: a candidate needs one of them as a whole word of the text.
    const words = statics.flatMap((s, i) => [...s.matchAll(/[A-Za-z]{4,}/g)].filter(m => (m.index > 0 || i === 0) && (m.index + m[0].length < s.length || i === n)).map(m => m[0]))
    list.push({ st: statics, kind, to, long, size: statics.join('').length, words })
  }
  list.sort((a, b) => b.size - a.size)
  const df = new Map<string, number>()
  for (const tp of list) for (const w of new Set(tp.words)) df.set(w, (df.get(w) ?? 0) + 1)
  byWord = new Map()
  always = []
  list.forEach((tp, i) => {
    // One index entry per template: its rarest word (the longest on a tie), so a text only meets the templates that can match it.
    const d = (x: string) => df.get(x) as number
    const w = tp.words.reduce<string | null>((a, b) => (a === null || d(b) < d(a) || (d(b) === d(a) && b.length > a.length) ? b : a), null)
    if (w === null) always.push(i)
    else byWord.set(w, [...(byWord.get(w) ?? []), i])
  })
  exact = map
  tpls = list
}

const CAP = 2048

/** Two-generation cache (about LRU, no per-hit churn): a hit in the old generation is promoted into the new one. */
type Gen<V> = { a: Map<string, V>; b: Map<string, V> }
const gen = <V>(): Gen<V> => ({ a: new Map(), b: new Map() })
function gset<V>(g: Gen<V>, key: string, value: V): void {
  if (g.a.size >= CAP) { g.b = g.a; g.a = new Map() }
  g.a.set(key, value)
}
function gget<V>(g: Gen<V>, key: string): V | undefined {
  const v = g.a.get(key) ?? g.b.get(key)
  if (v !== undefined && !g.a.has(key)) gset(g, key, v)
  return v
}
const memo = gen<string | null>()
const cache = gen<string>()

/** An all-capitals screen title ("COST", "ROLES & PERMISSIONS") that the dictionary only holds as Title Case or lower case. */
const CAPS = /^[A-Z][A-Z &-]*[A-Z]$/

/** Exact dictionary lookup of one stripped core; a capitals-only core also tries its Title Case and lower case forms. */
function ex(core: string): string | undefined {
  const map = exact as Map<string, string>
  const v = map.get(core)
  if (v !== undefined || core.length < 2 || !CAPS.test(core)) return v
  const low = core.toLowerCase()

  return map.get(low.replace(/(^|[ -])([a-z])/g, (_, a: string, b: string) => a + b.toUpperCase())) ?? map.get(low)
}

function tmpl(core: string): string | null {
  const seen = gget(memo, core)
  if (seen !== undefined) return seen
  const out = core.length > 400 ? null : scan(core)
  gset(memo, core, out)
  return out
}

/** Linear match: statics found left to right with indexOf, no backtracking. Returns the captures or null. */
function run(tp: Tpl, s: string): string[] | null {
  const st = tp.st
  const n = st.length - 1
  const end = s.length - (st[n] as string).length
  if (!s.startsWith(st[0] as string) || !s.endsWith(st[n] as string) || end < (st[0] as string).length + n) return null
  const caps: string[] = []
  let pos = (st[0] as string).length
  const okLast = (p: number) => p < end && (tp.kind[n - 1] === false || !/\s/.test(s.slice(p, end)))
  for (let i = 1; i < n; i++) {
    const mid = st[i] as string
    let at = s.indexOf(mid, pos + 1)
    for (let tries = 0; i === n - 1 && at >= 0 && tries < 8 && !okLast(at + mid.length); tries++) at = s.indexOf(mid, at + 1)
    if (at < 0 || (i === n - 1 && !okLast(at + mid.length))) return null
    caps.push(s.slice(pos, at))
    pos = at + mid.length
  }
  if (pos >= end) return null
  caps.push(s.slice(pos, end))
  return caps.some((c, k) => tp.kind[k] === true && /\s/.test(c)) ? null : caps
}

function scan(core: string): string | null {
  const found = new Set<number>(always)
  const seen = new Set(core.match(/[A-Za-z]{4,}/g) ?? [])
  for (const w of seen) for (const i of byWord.get(w) ?? []) found.add(i)
  const order = found.size > 1 ? [...found].sort((a, b) => a - b) : [...found]
  for (const i of order) {
    const tp = tpls[i] as Tpl
    if (!core.startsWith(tp.st[0] as string) || !core.endsWith(tp.st[tp.st.length - 1] as string) || !tp.words.every(w => seen.has(w)) || !core.includes(tp.long)) continue
    const m = run(tp, core)
    if (m === null) continue
    return tp.to.replace(/\{(\d+)\}/g, (_, k: string) => (ex(m[Number(k)] ?? '') ?? m[Number(k)]) as string)
  }

  return null
}

type Frame = { lead: string; core: string; tail: string }

/** Rule 5: peel leading space and symbols and trailing space; the core is what gets looked up, the peeled parts go back around the result. */
function frame(s: string): Frame {
  const c = s.charCodeAt(0)
  const lead = (c >= 65 && c <= 90) || (c >= 97 && c <= 122) || (c >= 48 && c <= 57) ? '' : (LEAD.exec(s) ?? [''])[0]
  const rest = lead === '' ? s : s.slice(lead.length)
  const core = rest.trimEnd()

  return { lead, core, tail: rest.slice(core.length) }
}

/** Exact then template on the core; null for an empty core. */
const hit = (core: string): string | null => (core === '' ? null : (ex(core) ?? tmpl(core)))

/** "left: right": each side by its own, the left as a title or phrase, the right only as an exact word. */
function colon(f: Frame): string | null {
  const at = f.core.indexOf(': ')
  if (at < 0) return null
  const lf = frame(f.core.slice(0, at))
  const rf = frame(f.core.slice(at + 2))
  const left = (o => (o === null ? null : lf.lead + o + lf.tail))(hit(lf.core))
  const right = (o => (o === undefined ? null : rf.lead + o + rf.tail))(rf.core === '' ? undefined : ex(rf.core))

  return left === null && right === null ? null : `${f.lead}${left ?? f.core.slice(0, at)}: ${right ?? f.core.slice(at + 2)}${f.tail}`
}

/** One line of a multi-line text. */
function unit(u: string): string {
  if (HANGUL.test(u)) return u
  const whole = ex(u)
  if (whole !== undefined) return whole
  const f = frame(u)
  const out = hit(f.core)

  return out !== null ? f.lead + out + f.tail : (colon(f) ?? u)
}

/** One line, whole: template first (on the core, then on the text as it is), then dictionary, then "left: right". */
function single(s: string): string {
  const f = frame(s)
  const t1 = f.core === '' ? null : tmpl(f.core)
  if (t1 !== null) return f.lead + t1 + f.tail
  const t2 = f.core === s ? null : tmpl(s)
  if (t2 !== null) return t2
  if (HANGUL.test(s)) return s
  const e = f.core === '' ? undefined : ex(f.core)

  return e !== undefined ? f.lead + e + f.tail : (colon(f) ?? s)
}

function lookup(s: string): string {
  const head = s.trimStart()
  if ((head.startsWith('{') || head.startsWith('[')) && s.trim() !== '') {
    try { JSON.parse(s); return s } catch { /* not JSON: carry on */ }
  }
  const direct = ex(s)
  if (direct !== undefined) return direct
  if (!s.includes('\n')) return single(s)
  const f = frame(s)
  const core = f.core === '' ? null : tmpl(f.core)
  if (core !== null) return f.lead + core + f.tail
  const wide = tmpl(s)
  if (wide !== null) return wide

  return s.split(/(\r?\n)/).map((p, i) => (i % 2 === 1 ? p : unit(p))).join('')
}

/** Translates one text: dictionary exact, template, then line by line. Anything unknown comes back as it was. */
export function t(text: string): string {
  try {
    if (locale !== 'ko' || typeof text !== 'string' || text.length === 0 || text.length > 2000) return text
    if (exact === null) compile()
    const out = gget(cache, text) ?? lookup(text)
    gset(cache, text, out)
    return out
  } catch { return text }
}

/** Text of any length: up to 2000 characters it is t; longer, it is cut into lines (\r\n kept) and each line goes through t. JSON stays as it was. */
export function tLines(text: string): string {
  try {
    if (locale !== 'ko' || typeof text !== 'string' || text.length <= 2000) return t(text)
    const head = text.trimStart()
    if (head.startsWith('{') || head.startsWith('[')) {
      try { JSON.parse(text); return text } catch { /* not JSON: carry on */ }
    }

    return text.split(/(\r?\n)/).map((p, i) => (i % 2 === 1 ? p : t(p))).join('')
  } catch { return text }
}

/** Exact dictionary match only (a capitals-only title also by its Title Case or lower case form), symbols and spaces around it peeled and put back: no template, no "left: right", no line splitting. For user data. */
export function tExact(text: string): string {
  try {
    if (locale !== 'ko' || typeof text !== 'string' || text.length === 0 || text.length > 2000) return text
    if (exact === null) compile()
    const whole = ex(text)
    if (whole !== undefined) return whole
    const f = frame(text)
    const out = f.core === '' ? undefined : ex(f.core)

    return out === undefined ? text : f.lead + out + f.tail
  } catch { return text }
}

const ZERO: [number, number][] = [[0x300, 0x36f], [0x200b, 0x200f], [0xfe00, 0xfe0f], [0x20e3, 0x20e3]]
// Sorted. Wide: East Asian wide, all of the emoji planes, and the BMP symbols that are emoji by default (the rest of them turn wide with U+FE0F).
const WIDE: [number, number][] = [
  [0x1100, 0x115f], [0x231a, 0x231b], [0x23e9, 0x23ec], [0x23f0, 0x23f0], [0x23f3, 0x23f3], [0x25fd, 0x25fe], [0x2614, 0x2615], [0x2648, 0x2653], [0x267f, 0x267f], [0x2693, 0x2693],
  [0x26a1, 0x26a1], [0x26aa, 0x26ab], [0x26bd, 0x26be], [0x26c4, 0x26c5], [0x26ce, 0x26ce], [0x26d4, 0x26d4], [0x26ea, 0x26ea], [0x26f2, 0x26f3], [0x26f5, 0x26f5], [0x26fa, 0x26fa],
  [0x26fd, 0x26fd], [0x2705, 0x2705], [0x270a, 0x270b], [0x2728, 0x2728], [0x274c, 0x274c], [0x274e, 0x274e], [0x2753, 0x2755], [0x2757, 0x2757], [0x2795, 0x2797], [0x27b0, 0x27b0],
  [0x27bf, 0x27bf], [0x2b1b, 0x2b1c], [0x2b50, 0x2b50], [0x2b55, 0x2b55], [0x2e80, 0x303e], [0x3041, 0x33ff], [0x3400, 0x4dbf], [0x4e00, 0x9fff], [0xa960, 0xa97f], [0xac00, 0xd7a3],
  [0xf900, 0xfaff], [0xfe30, 0xfe4f], [0xff00, 0xff60], [0xffe0, 0xffe6], [0x1f300, 0x1faff], [0x20000, 0x3fffd],
]
const within = (c: number, ranges: [number, number][]) => ranges.some(([a, b]) => c >= a && c <= b)

/** Display width: East Asian wide characters and emoji count 2 in Korean (U+FE0F widens the character before it, and is itself 0), plain length in English. */
export function widthOf(s: string): number {
  try {
    if (typeof s !== 'string') s = String(s ?? '')
    if (locale !== 'ko') return s.length
    let w = 0
    let prev = 0
    for (const ch of s) {
      const c = ch.codePointAt(0) as number
      if (c === 0xfe0f) {
        if (prev === 1) { w += 1; prev = 2 }
        continue
      }
      const cw = c < 0x300 ? 1 : within(c, ZERO) ? 0 : within(c, WIDE) ? 2 : 1
      w += cw
      if (cw > 0) prev = cw
    }

    return w
  } catch { return 0 }
}
export function padEndW(s: string, n: number): string {
  try { return locale !== 'ko' ? s.padEnd(n) : s + ' '.repeat(Math.max(0, n - widthOf(s))) } catch { return s }
}

const tc = (children: unknown): unknown => (typeof children === 'string' ? t(children) : Array.isArray(children) ? children.map(c => (typeof c === 'string' ? t(c) : c)) : children)

/** English: the same kit. Korean: Text children, Button labels and children, and Input labels run through t, and the kit carries the mark. */
export function withLocale<K extends object>(kit: K): K {
  try {
    if (locale !== 'ko' || isLocalized(kit)) return kit
    type Fn = (p: Record<string, unknown>) => unknown
    const k = kit as unknown as Record<string | symbol, Fn | undefined>
    const tx = (p: Record<string, unknown>, keys: string[]) => {
      const next = { ...(p ?? {}) }
      for (const key of keys) if (typeof next[key] === 'string') next[key] = t(next[key] as string)
      return next
    }
    const wrap = (orig: Fn, map: Fn): Fn => props => {
      let next = props
      try { next = map(props) as Record<string, unknown> } catch { /* keep the original props */ }
      return orig(next)
    }
    const out: Record<string | symbol, unknown> = { ...k, [I18N_MARK]: true }
    if (k.Text !== undefined) out.Text = wrap(k.Text, p => {
      // verbatim: data the caller already resolved (e.g. a kv value) is drawn as given, and the prop never reaches the host.
      if (p && p.verbatim === true) { const { verbatim: _v, ...rest } = p; return rest }
      return 'children' in (p ?? {}) ? { ...p, children: tc(p.children) } : { ...(p ?? {}) }
    })
    if (k.Button !== undefined) out.Button = wrap(k.Button, p => { const q = tx(p, ['label']); return 'children' in q ? { ...q, children: tc(q.children) } : q })
    if (k.Input !== undefined) out.Input = wrap(k.Input, p => tx(p, ['label', 'placeholder', 'submitLabel']))
    return out as unknown as K
  } catch { return kit }
}
export function isLocalized(kit: object): boolean {
  return kit != null && typeof kit === 'object' && (kit as Record<symbol, unknown>)[I18N_MARK] === true
}
