#!/usr/bin/env node
// 번역 샤드 → 런타임 사전 생성기 (계획 §2.5, §4.2.2, §4.7 B2).
//   node scripts/i18n/build.mjs [--dry-run] [--check] [--repo <dir>]
// 만드는 것:
//   - v3/@claude-flow/cli/i18n/ko/{help,messages}.json   (스키마 ruflo-i18n-dict/1)
//   - plugins/<p>/hooks/i18n/{translate.ts, ko-dict.ts, ko-dict-NN.ts}  (<p> 는 i18n/ko/plugins/ 아래 폴더)
// 규칙:
//   - 번역이 있는(ko 가 비지 않은 문자열) 항목만 사전에 넣는다. null·"" 은 영어 유지.
//   - 중복 제거는 런타임 사전 단위 안에서만(CLI: help+messages 묶음 1개, 플러그인: 각 1개). 첫 출현 샤드가 키를 소유한다.
//   - 같은 입력이면 같은 바이트(키는 정렬, 청크는 순서대로 450개씩).
//   - --dry-run: 쓰지 않고 보고만. --check: 쓰지 않고 디스크와 다르면 exit 1.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { REPO as DEFAULT_REPO } from './lib/ts-resolve.mjs';
import { cmp, stableJson, readJson } from './lib/shard-io.mjs';

export const CHUNK_MAX = 450;
export const LINE_MAX = 500;
export const GEN_HEADER = '// GENERATED by scripts/i18n/templates/plugin-translate.ts - do not edit; edit the source and copy it again.\n';
export const DICT_HEADER = '// GENERATED by scripts/i18n/build.mjs - do not edit; edit i18n/ko/plugins/<plugin>/*.json and run build again.\n';
export const STUB = '// Stub: build.mjs regenerates this file from the ko-dict-NN.ts chunks. Until then the dictionary is empty and every text stays English.\nexport const KO: Record<string, string> = {}\n';
export const CLI_OUT = 'v3/@claude-flow/cli/i18n/ko';
export const TEMPLATE_REL = 'scripts/i18n/templates/plugin-translate.ts';

function listJsonAbs(dirAbs) {
  const out = [];
  const walk = (d) => {
    let names;
    try {
      names = fs.readdirSync(d, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of names) {
      const p = path.join(d, e.name);
      if (e.isDirectory()) walk(p);
      else if (e.name.endsWith('.json')) out.push(p);
    }
  };
  walk(dirAbs);
  return out.sort((a, b) => cmp(a.split(path.sep).join('/'), b.split(path.sep).join('/')));
}

/** 한 런타임 단위의 샤드들(정렬된 순서)에서 { key → ko }. 소유권은 첫 출현 샤드가 갖는다(번역이 없어도 키를 점유).
 *  소유 샤드의 ko 가 null 이면 의도적으로 영어를 유지하는 것이므로 뒤 샤드의 번역을 채택하지 않는다(LOW-1).
 *  소유 샤드의 ko 가 "" (아직 미번역)일 때만 뒤 샤드의 번역을 채택한다. */
function unitDictOwned(shardFiles, owned) {
  const dict = new Map();
  for (const f of shardFiles) {
    const sh = readJson(f);
    if (!sh || !Array.isArray(sh.entries)) continue;
    for (const e of sh.entries) {
      if (!e || typeof e.key !== 'string') continue;
      const has = typeof e.ko === 'string' && e.ko !== '';
      if (owned.has(e.key)) {
        const o = owned.get(e.key);
        if (!dict.has(e.key) && has && !o.translated && !o.keepEnglish) {
          o.translated = true;
          dict.set(e.key, e.ko);
        }
        continue;
      }
      owned.set(e.key, { translated: has, keepEnglish: e.ko === null });
      if (has) dict.set(e.key, e.ko);
    }
  }
  return dict;
}

/** TS 문자열 리터럴(큰따옴표). smoke 정규식에 걸리는 부분은 유니코드 이스케이프로 바꾼다(§4.2.2). */
export function tsLiteral(s, { escapeSep = false } = {}) {
  let lit = JSON.stringify(s)
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029')
    .replace(/Buffer/g, '\\u0042uffer')
    .replace(/import\(/g, 'import\\u0028')
    .replace(/require\(/g, 'require\\u0028')
    .replace(/node:/g, 'node\\u003a')
    // 플러그인 smoke 의 정적 검사(console 9, mods 4·5·7·12): $.ui. $.env. $.http. $.process. $.model. $.mcp. $.fs. 와 on(' (MEDIUM-8)
    .replace(/\$(?=\.(?:ui|env|http|process|model|mcp|fs)\.)/g, '\\u0024')
    .replace(/\bon\(/g, 'on\\u0028');
  if (escapeSep) lit = lit.replace(/:/g, '\\u003a').replace(/=/g, '\\u003d');
  return lit;
}

const SECRET_RE = /(api[_-]?key|secret|password|token)\s*[:=]\s*['"][^'"]{8,}/i;

function entryLine(k, v) {
  let line = `  ${tsLiteral(k)}: ${tsLiteral(v)},`;
  if (SECRET_RE.test(line)) line = `  ${tsLiteral(k, { escapeSep: true })}: ${tsLiteral(v, { escapeSep: true })},`;
  return line;
}

export function chunkName(i) {
  return `ko-dict-${String(i + 1).padStart(2, '0')}`;
}

/** 플러그인 한 개의 생성 파일들: Map<repo 기준 상대경로, 텍스트> */
function pluginFiles(repo, plugin, dict, template) {
  const base = `plugins/${plugin}/hooks/i18n`;
  const files = new Map();
  files.set(`${base}/translate.ts`, GEN_HEADER + template);
  const keys = [...dict.keys()].sort(cmp);
  const chunks = [];
  const chunkLines = [];
  for (let i = 0; i < keys.length; i += CHUNK_MAX) chunks.push(keys.slice(i, i + CHUNK_MAX));
  if (!chunks.length) {
    files.set(`${base}/ko-dict.ts`, STUB);
  } else {
    chunks.forEach((ks, i) => {
      const name = `KO_${String(i + 1).padStart(2, '0')}`;
      const text = `${DICT_HEADER}export const ${name}: Record<string, string> = {\n${ks.map((k) => entryLine(k, dict.get(k))).join('\n')}\n}\n`;
      files.set(`${base}/${chunkName(i)}.ts`, text);
      chunkLines.push(text.split('\n').length - 1); // 실제 파일 줄 수(머리말·선언·닫는 줄 포함)
    });
    const imports = chunks.map((_, i) => `import { KO_${String(i + 1).padStart(2, '0')} } from './${chunkName(i)}'`).join('\n');
    const names = chunks.map((_, i) => `KO_${String(i + 1).padStart(2, '0')}`).join(', ');
    files.set(`${base}/ko-dict.ts`, `${DICT_HEADER}${imports}\nexport const KO: Record<string, string> = {}\nObject.assign(KO, ${names})\n`);
  }
  return { files, chunks: chunks.length, entries: keys.length, chunkLines };
}

/**
 * 생성 계획. 디스크는 읽기만 한다.
 * 반환: { files: Map<rel, text>, remove: [rel], stats }
 */
export function plan({ repo = DEFAULT_REPO } = {}) {
  const ko = path.join(repo, 'i18n/ko');
  const files = new Map();
  const stats = { cli: {}, plugins: {} };
  // CLI: help 샤드가 먼저, 그다음 messages 샤드. 한 묶음으로 중복 제거.
  const owned = new Map();
  const helpFiles = listJsonAbs(path.join(ko, 'cli/help'));
  const msgFiles = listJsonAbs(path.join(ko, 'cli/messages'));
  const help = unitDictOwned(helpFiles, owned);
  const msgs = unitDictOwned(msgFiles, owned);
  for (const [name, dict] of [['help', help], ['messages', msgs]]) {
    const entries = {};
    for (const k of [...dict.keys()].sort(cmp)) entries[k] = dict.get(k);
    files.set(`${CLI_OUT}/${name}.json`, stableJson({ schema: 'ruflo-i18n-dict/1', locale: 'ko', entries }));
    stats.cli[name] = { shards: name === 'help' ? helpFiles.length : msgFiles.length, entries: dict.size };
  }
  // 플러그인
  let template = '';
  try {
    template = fs.readFileSync(path.join(repo, TEMPLATE_REL), 'utf8');
  } catch {
    template = null;
  }
  const remove = [];
  let plugins = [];
  try {
    plugins = fs.readdirSync(path.join(ko, 'plugins'), { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name).sort(cmp);
  } catch { /* 플러그인 샤드 없음 */ }
  for (const p of plugins) {
    const shardFiles = listJsonAbs(path.join(ko, 'plugins', p));
    const dict = unitDictOwned(shardFiles, new Map());
    if (template === null) {
      stats.plugins[p] = { shards: shardFiles.length, entries: dict.size, chunks: 0, error: `정본 없음: ${TEMPLATE_REL}` };
      continue;
    }
    const r = pluginFiles(repo, p, dict, template);
    for (const [k, v] of r.files) files.set(k, v);
    stats.plugins[p] = { shards: shardFiles.length, entries: r.entries, chunks: r.chunks, maxChunkLines: Math.max(0, ...r.chunkLines) };
    // 더 이상 필요 없는 청크 파일
    const dirAbs = path.join(repo, `plugins/${p}/hooks/i18n`);
    try {
      for (const n of fs.readdirSync(dirAbs)) {
        const rel = `plugins/${p}/hooks/i18n/${n}`;
        if (/^ko-dict-\d+\.ts$/.test(n) && !files.has(rel)) remove.push(rel);
      }
    } catch { /* 폴더 없음 */ }
  }
  return { files, remove: remove.sort(cmp), stats, repo };
}

/** 디스크와 비교: { changed: [rel], missing: [rel], removed: [rel] } */
export function diffPlan(p) {
  const changed = [];
  for (const [rel, text] of p.files) {
    let cur = null;
    try {
      cur = fs.readFileSync(path.join(p.repo, rel), 'utf8');
    } catch { /* 새 파일 */ }
    if (cur !== text) changed.push(rel);
  }
  return { changed: changed.sort(cmp), removed: p.remove };
}

export function apply(p) {
  for (const [rel, text] of p.files) {
    const abs = path.join(p.repo, rel);
    let cur = null;
    try {
      cur = fs.readFileSync(abs, 'utf8');
    } catch { /* 새 파일 */ }
    if (cur === text) continue;
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, text);
  }
  for (const rel of p.remove) {
    try {
      fs.unlinkSync(path.join(p.repo, rel));
    } catch { /* 이미 없음 */ }
  }
}

function main() {
  const argv = process.argv.slice(2);
  const flag = (n) => argv.includes(n);
  const ri = argv.indexOf('--repo');
  const repo = ri >= 0 ? path.resolve(argv[ri + 1]) : DEFAULT_REPO;
  const dry = flag('--dry-run');
  const check = flag('--check');
  const p = plan({ repo });
  const d = diffPlan(p);
  console.log(`build: repo=${repo}`);
  console.log(`CLI 사전: help ${p.stats.cli.help.entries}항목 (샤드 ${p.stats.cli.help.shards}), messages ${p.stats.cli.messages.entries}항목 (샤드 ${p.stats.cli.messages.shards})`);
  let chunkTotal = 0;
  let maxLines = 0;
  let bad = 0;
  for (const [name, s] of Object.entries(p.stats.plugins)) {
    if (s.error) {
      console.log(`  ${name}: ${s.error}`);
      bad++;
      continue;
    }
    chunkTotal += s.chunks;
    maxLines = Math.max(maxLines, s.maxChunkLines || 0);
    console.log(`  ${name}: ${s.entries}항목, 청크 ${s.chunks}개 (샤드 ${s.shards}), 청크 최대 ${s.maxChunkLines || 0}줄`);
  }
  for (const [rel, text] of p.files) {
    const n = text.split('\n').length - 1;
    if (rel.endsWith('.ts') && /ko-dict/.test(rel) && n > LINE_MAX) {
      console.log(`  초과: ${rel} ${n}줄 > ${LINE_MAX}`);
      bad++;
    }
  }
  console.log(`청크 합계 ${chunkTotal}개, 가장 긴 청크 ${maxLines}줄 (한도 ${LINE_MAX}줄), 생성 파일 ${p.files.size}개, 바뀔 파일 ${d.changed.length}개, 지울 파일 ${d.removed.length}개`);
  if (dry || check) {
    if (dry && d.changed.length) for (const r of d.changed.slice(0, 20)) console.log(`  변경 예정: ${r}`);
    if (check && (d.changed.length || d.removed.length)) {
      console.error('STALE_DICT: 생성물이 샤드와 다릅니다. node scripts/i18n/build.mjs 를 실행하세요.');
      process.exit(1);
    }
    process.exit(bad ? 1 : 0);
  }
  if (bad) process.exit(1);
  apply(p);
  console.log('쓰기 완료');
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
